### ISSUE TITLE
Clarifying things

### ISSUE THREAD

**Issue by xfynx** [CI-HUB-GmbH/SimpleRESTAdapterBundle#3]
Hello!
First of all, i wanted to say thanks for your plugin, it's really useful!
It's not really an issue, i just wanted to clarify a couple of things cause there is no documentation for it. Apologies for that!
I plan to gather all the knowledge and write additional documentation, which I hope will be useful for future library users.

So, questions:
1. Do I understand correctly that if i want to add other routes or to change output json format, i need to write my own custom controller? And by default the only way to fetch data is to use these endpoints (see picture below)?
![изображение](https://user-images.githubusercontent.com/3057907/158313090-51eefebd-d4e0-4645-b7d3-3e5f29231d22.png)

2. The main struggle for us at the moment is the relation data.
![изображение](https://user-images.githubusercontent.com/3057907/158313517-ff46bdd0-1c54-4090-bef9-a1a90be87567.png)
At the picture above you can see fields `data->color` and `data->size` which are related objects. I have defined schema definitions for each of them (picture below).
![изображение](https://user-images.githubusercontent.com/3057907/158313637-9727ca36-25a2-4cb2-9328-0097dde124b3.png)
I expected it to work similar way to datahub's grapqhl configuration - you define schemas and fetch related data inside as json too.
But in the response through REST API i have only string that points to an object.
Is there any solution to expand it somehow? I need it to look like `data->color->{.....}`, not a string.

Once again, I apologize for not using issued correctly and thanks in advance! If there will be enough information, i'll create PR with documentation on how to properly configure bundle with docker and all the knowledges regarding configuration.

**Comment by aarongerig** [comment]
Hi @xfynx,

1. These are the only three endpoints provided by this bundle. If you need more or any other custom endpoints, you can add them yourself in one of your controllers. This bundle only provides a "simple" and also generic REST integration into Pimcore.

2. For relational data, you have to make another REST call in order to fetch the data of the related DataObject or Asset. REST does not work the same as GraphQL where you can retrieve all the data you need in one call. That's actually also one of the drawbacks of using a REST API.

If you have any other questions, please let me know. If not, you can close the issue. Thank you! :)

**Comment by xfynx** [comment]
Hi @aarongerig! Thank you for the detailed answer!
Yes, now it's clear, i'll close the issue and later in the next few days i'll add some documentation just like i promised earlier
