### ISSUE TITLE
Use without Elasticsearch?

### ISSUE THREAD

**Issue by NiklasBr** [CI-HUB-GmbH/SimpleRESTAdapterBundle#5]
Would it be possible to use this bundle without Elasticsearch and accept that performance is slower because of regular Pimcore Data Object Listings? Or use another search provider like Algolia?

**Comment by aarongerig** [comment]
Hi @NiklasBr !
As of right now the usage of Elasticsearch in combination with this bundle is mandatory, otherwise the data cannot be indexed or queried. I'm sure it would also be possible to create some kind of "adapter system", where the developer could choose from different storage adapters (like Pimcore DB directly, Algolia, Elasticsearch, etc.).
Although, this is something that is not on our TODO list unfortunately, but we are always open to contributions.
Hope this answers your question, otherwise please let us know.
